auth_enabled: false

target: all,table-manager

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    alibabacloud:
        bucket: xxxxxxxx
        endpoint: oss-ap-southeast-5-internal.aliyuncs.com
        access_key_id: xxxxxxxx
        secret_access_key: xxxxxxxx
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
  - from: 2023-05-01
    store: boltdb-shipper
    object_store: alibabacloud
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  alibabacloud:
    bucket: xxxxxxxx
    endpoint: oss-ap-southeast-5-internal.aliyuncs.com
    access_key_id: xxxxxxxx
    secret_access_key: xxxxxxxx

compactor:
  shared_store: filesystem
  retention_enabled: true

limits_config:
  retention_period: 180d
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 180d

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 180d

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
