---
version: "3.9"
services:
  mongo:
    image: mongo:4.4.2
    ports:
      - xxxxxxxx:27017
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - mongo:/data/db
    networks:
      - public
    environment:
      MONGO_INITDB_ROOT_USERNAME: xxxxxxxx
      MONGO_INITDB_ROOT_PASSWORD: xxxxxxxx

  mongo-express:
    image: mongo-express:latest
    ports:
      - xxxxxxxx:8081
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: xxxxxxxx
      ME_CONFIG_MONGODB_ADMINUSERNAME: xxxxxxxx
      ME_CONFIG_MONGODB_URL=mongodb: //mongo_admin:xxxxxxxx:port/
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

    networks:
      - public
    deploy:


networks:
  public:
    external: true

volumes:
  mongo:
