version: '3.9'

services:
  agent:
    image: portainer/agent:2.17.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - public
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ee:2.17.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "xxxxxxxx:9443"
      - "xxxxxxxx:9000"
      - "xxxxxxxx:8000"
    volumes:
      - portainer_data:/data
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  public:
    external: true

volumes:
  portainer_data:
