version: '3.8'
services:
    redis:
        image: redis:7.0.8
        command: redis-server --requirepass xxxxxxxx
        ports:
        -   target: 6379
            published: xxxxxxxx
            protocol: tcp
            mode: ingress
        networks:
        -   public
        volumes:
        -   redis-data:/data
volumes:
  redis-data:
networks:
  public:
    external: true
