# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: 
        - localhost:9090
  
  - job_name: devops_central
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.64.77:8080
        
  - job_name: BE_Production
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.88.200:9080
  
  - job_name: VM_devops_central
    scrape_interval: 5s
    static_configs:
      - targets:
        - node-exporter:9100
        
  - job_name: Development_Swarm
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.64.72:5000
  
  - job_name: VM BE_Production
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.88.200:5000
  
  - job_name: VM FE_Production
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.88.100:5000
  
  # - job_name: VM FE_development
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets:
  #       - 172.31.64.69:5000
        
  - job_name: development_swarm
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets:
        - 172.31.64.72:9080

  # - job_name: FE_development
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets:
  #       - 172.31.64.69:9080
  
  - job_name: FE_Production
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.88.100:9080
  
  - job_name: Data-Development
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.88.197:9100

  - job_name: Data-Production
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.88.205:9100
  
  - job_name: PM-Data-Tableau
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.31.88.178:9100
