version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    ports:
      - "2945:9090"
    volumes:
      - prometheus-data:/prometheus
      - prometheus-config:/etc/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.size=5GB'
      - '--web.enable-lifecycle'
    networks:
      - public
  
  grafana:
    image: grafana/grafana:9.4.1
    container_name: grafana
    ports:
      - "6438:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - public
      

networks:
  public:
    external: true
    name: public
volumes:
  prometheus-data:
  prometheus-config:
  grafana-data:
