version: '3.9'

services:

  konga-database:
    image: postgres:10.23-alpine
    environment:
      POSTGRES_USER: 'xxxxxxxx'
      POSTGRES_DB: 'xxxxxxxx'
      POSTGRES_PASSWORD: 'xxxxxxxx'
      PGDATA: '/data/postgres'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - konga-database:/data/postgres
    # ports:
    #   - target: 5432
    #     published: 5432
    #     protocol: tcp
    #     mode: ingress
    networks:
      - konga
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 4G

networks:
  konga:
    external: true
    name: konga

volumes:
    konga-database:
      external: true
      name: konga-database